FROM golang:1.22-bookworm AS builder

WORKDIR /src
COPY . .

ARG APP_PATH
WORKDIR /src/${APP_PATH}
RUN go mod download
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o /out/service .

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates libsqlite3-0 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /out/service /app/service
COPY data /app/data

EXPOSE 8001 8002 8003 8004 8010
CMD ["/app/service"]
